server:
  port: 9991
spring:
  datasource:
    url: jdbc:mariadb://westworld:30006/overengineered-todo
    username: root
    password: secretpassword
    initialization-mode: always
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: westworld
    port: 31672
    username: admin
    password: admin