server:
  port: 9991
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/overengineered-todo
    username: root
    password: password
    initialization-mode: always
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true