server:
  port: 9991
spring:
  datasource:
    url: jdbc:mariadb://192.168.0.144:30006/overengineered-todo
    username: root
    password: secretpassword
    initialization-mode: always
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true

management:
  health:
    probes:
      enabled: true