apiVersion: v1
kind: Service
metadata:
  name: {{ include "oe-todo-tasks-deploy.fullname" . }}-nodeport
  labels:
    {{- include "oe-todo-tasks-deploy.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "oe-todo-tasks-deploy.selectorLabels" . | nindent 4 }}
